"""create payment attempts table

Revision ID: 190fac7c4674
Revises: 2fb5ca20ad9a
Create Date: 2026-08-14 19:09:03.964075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '190fac7c4674'
down_revision: Union[str, Sequence[str], None] = '2fb5ca20ad9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_attempts',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('group_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('settlement_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('payer_user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('receiver_user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('payment_reference', sa.String(length=150), nullable=True),
    sa.Column('upi_uri', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payer_user_id', 'idempotency_key', name='uq_payment_payer_idempotency')
    )
    op.create_index(op.f('ix_payment_attempts_group_id'), 'payment_attempts', ['group_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_payer_user_id'), 'payment_attempts', ['payer_user_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_receiver_user_id'), 'payment_attempts', ['receiver_user_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_settlement_id'), 'payment_attempts', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_status'), 'payment_attempts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_attempts_status'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_settlement_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_receiver_user_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_payer_user_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_group_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    # ### end Alembic commands ###
