"""add payment attempts

Revision ID: 2fb5ca20ad9a
Revises: a3ba5e53e140
Create Date: 2026-08-14 18:36:34.839765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb5ca20ad9a'
down_revision: Union[str, Sequence[str], None] = 'a3ba5e53e140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
