"""add expense item tables

Revision ID: 478a9b953d0d
Revises: f27c73414f10
Create Date: 2026-08-13 20:59:07.529066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '478a9b953d0d'
down_revision: Union[str, Sequence[str], None] = 'f27c73414f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_items',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('expense_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_items_expense_id'), 'expense_items', ['expense_id'], unique=False)
    op.create_table('expense_item_participants',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('item_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('share_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['expense_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'user_id', name='uq_expense_item_participant')
    )
    op.create_index(op.f('ix_expense_item_participants_item_id'), 'expense_item_participants', ['item_id'], unique=False)
    op.create_index(op.f('ix_expense_item_participants_user_id'), 'expense_item_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_item_participants_user_id'), table_name='expense_item_participants')
    op.drop_index(op.f('ix_expense_item_participants_item_id'), table_name='expense_item_participants')
    op.drop_table('expense_item_participants')
    op.drop_index(op.f('ix_expense_items_expense_id'), table_name='expense_items')
    op.drop_table('expense_items')
    # ### end Alembic commands ###
