"""add settlements

Revision ID: a3ba5e53e140
Revises: 478a9b953d0d
Create Date: 2026-08-13 22:51:44.128158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3ba5e53e140'
down_revision: Union[str, Sequence[str], None] = '478a9b953d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('group_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('from_user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('to_user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=150), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_from_user_id'), 'settlements', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_settlements_group_id'), 'settlements', ['group_id'], unique=False)
    op.create_index(op.f('ix_settlements_status'), 'settlements', ['status'], unique=False)
    op.create_index(op.f('ix_settlements_to_user_id'), 'settlements', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlements_to_user_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_status'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_group_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_from_user_id'), table_name='settlements')
    op.drop_table('settlements')
    # ### end Alembic commands ###
