"""add user upi fields

Revision ID: f50da0790575
Revises: 190fac7c4674
Create Date: 2026-08-14 19:42:24.205844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50da0790575'
down_revision: Union[str, Sequence[str], None] = '190fac7c4674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('upi_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('upi_verified', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_upi_id'), 'users', ['upi_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_upi_id'), table_name='users')
    op.drop_column('users', 'upi_verified')
    op.drop_column('users', 'upi_id')
    # ### end Alembic commands ###
